
import { Word, Category } from './types';

const createWord = (id: string, it: string, cn: string, category: Category): Word => ({
  id, it, cn, category,
  interval: 0,
  easeFactor: 2.5,
  nextReviewDate: 0,
  repetition: 0
});

export const INITIAL_VOCABULARY: Word[] = [
  // --- USER RECORD DATA (基于学习记录文档) ---
  createWord("u0", "a causa di", "由于/因为", Category.RULES),
  createWord("u1", "abbagliamento", "眩光/耀眼", Category.BEHAVIOR),
  createWord("u2", "abbagliante", "大灯/耀眼的", Category.VEHICLE),
  createWord("u4", "abbagliare", "使眼花/使目眩", Category.BEHAVIOR),
  createWord("u5", "abbandonare", "离开/离弃/放弃", Category.BEHAVIOR),
  createWord("u6", "abbassare", "降低/放低", Category.RULES),
  createWord("u8", "abbinare", "结合/合并", Category.RULES),
  createWord("u10", "abile", "有能力的", Category.DOCUMENTS),
  createWord("u12", "abusivamente", "非法/滥用地", Category.DOCUMENTS),
  createWord("u13", "accanto", "在旁边", Category.GENERAL),
  createWord("u15", "accelerazione", "加速", Category.BEHAVIOR),
  createWord("u16", "accensione", "点火/启动", Category.VEHICLE),
  createWord("u17", "accertamento", "核实/调查", Category.DOCUMENTS),
  createWord("u20", "accesso", "入口/进入", Category.ROAD_SIGNS),
  createWord("u22", "accostamento", "靠边", Category.BEHAVIOR),
  createWord("u23", "acustico", "声音的/听觉的", Category.BEHAVIOR),
  createWord("u24", "addetto", "工作人员/人员", Category.GENERAL),
  createWord("u27", "aderenza", "抓地力", Category.SAFETY),
  createWord("u31", "affinche", "为了/使得", Category.RULES),
  createWord("u33", "agente", "警察/执法者", Category.RULES),
  createWord("u34", "agevolare", "提供方便/帮助", Category.RULES),
  createWord("u36", "agganciamento", "系上/挂钩", Category.SAFETY),
  createWord("u39", "agricolo", "农业的", Category.VEHICLE),
  createWord("u47", "alternato", "交替/变换的", Category.ROAD_SIGNS),
  createWord("u48", "altrui", "他人的", Category.GENERAL),
  createWord("u52", "ammesso", "允许/接纳", Category.RULES),
  createWord("u57", "appoggiatesta", "头枕", Category.VEHICLE),
  createWord("u58", "apposito", "专门的/适合的", Category.GENERAL),
  createWord("u61", "arrestare", "停车/停止", Category.BEHAVIOR),
  createWord("u64", "articolo", "条文/条款", Category.DOCUMENTS),
  createWord("u67", "asse", "轴/轮轴/中心线", Category.VEHICLE),
  createWord("u71", "assicurazione", "保险", Category.DOCUMENTS),
  createWord("u78", "attraversamento", "横道/交叉口", Category.ROAD_SIGNS),
  createWord("u81", "aumentare", "增加", Category.RULES),
  createWord("u83", "autocarro", "货车/卡车", Category.VEHICLE),
  createWord("u84", "autocisterna", "油罐车", Category.VEHICLE),
  createWord("u85", "autorizzare", "许可/授权", Category.DOCUMENTS),
  createWord("u89", "autovelox", "测速照相", Category.RULES),
  createWord("u90", "avaria", "故障/损坏", Category.VEHICLE),
  createWord("u93", "avviare", "启动/开始", Category.VEHICLE),
  createWord("u100", "banchina", "路肩/月台", Category.GENERAL),
  createWord("u103", "barriera", "障碍物/栅栏", Category.ROAD_SIGNS),
  createWord("u106", "binario", "铁轨/轨道", Category.ROAD_SIGNS),
  createWord("u107", "bivio", "分岔口", Category.ROAD_SIGNS),
  createWord("u113", "cambio di velocità", "变速箱", Category.VEHICLE),
  createWord("u116", "cantiere", "施工/工地", Category.ROAD_SIGNS),
  createWord("u121", "cartello", "路标/牌子", Category.ROAD_SIGNS),
  createWord("u123", "casello", "收费站", Category.ROAD_SIGNS),
  createWord("u125", "cassone", "货车箱", Category.VEHICLE),
  createWord("u127", "catena", "防滑链/铁链", Category.VEHICLE),
  createWord("u131", "cedevole", "松软的", Category.GENERAL),
  createWord("u138", "cilindrata", "排气量", Category.VEHICLE),
  createWord("u139", "circolare", "通行/流动", Category.RULES),
  createWord("u142", "codice della strada", "道路交通法规", Category.DOCUMENTS),
  createWord("u149", "centro commerciale", "购物中心", Category.GENERAL),
  createWord("u167", "confluenza", "汇入/交汇点", Category.ROAD_SIGNS),
  createWord("u185", "contro mano", "逆行", Category.BEHAVIOR),
  createWord("u197", "cunetta", "排水沟/凹形路面", Category.ROAD_SIGNS),
  createWord("u208", "delimitare", "划定界限", Category.ROAD_SIGNS),
  createWord("u218", "deviazione", "偏离/绕行", Category.ROAD_SIGNS),
  createWord("u229", "diritto", "权利/先行权", Category.RULES),
  createWord("u232", "discesa", "下坡/下车", Category.ROAD_SIGNS),
  createWord("u241", "distanza", "距离/安全距离", Category.BEHAVIOR),
  createWord("u248", "divieto", "禁止", Category.ROAD_SIGNS),
  createWord("u252", "dosso", "隆起/凸起路段", Category.ROAD_SIGNS),
  createWord("u257", "effettuare", "进行/实现", Category.RULES),
  createWord("u262", "emissione", "排放/散发", Category.VEHICLE),
  createWord("u282", "evitare", "避免", Category.BEHAVIOR),
  createWord("u288", "feriale", "工作日", Category.GENERAL),
  createWord("u299", "frenare", "刹车/制动", Category.VEHICLE),
  createWord("u304", "frizione", "离合器", Category.VEHICLE),
  createWord("u317", "gradino", "台阶", Category.GENERAL),
  createWord("u330", "immatricolare", "注册/登记", Category.DOCUMENTS),
  createWord("u333", "immissione", "汇入/进入", Category.ROAD_SIGNS),
  createWord("u351", "incanalamento", "疏导/分流", Category.ROAD_SIGNS),
  createWord("u370", "ingorgo", "塞车/道路堵塞", Category.RULES),
  createWord("u389", "inversione", "调头", Category.BEHAVIOR),
  createWord("u402", "larghezza", "宽度", Category.GENERAL),
  createWord("u421", "mantenere", "保持", Category.BEHAVIOR),
  createWord("u423", "marcia", "行驶/档位", Category.VEHICLE),
  createWord("u443", "Motorizzazione civile", "交通局", Category.DOCUMENTS),
  createWord("u450", "obbligo", "义务/职责标志", Category.ROAD_SIGNS),
  createWord("u482", "pedaggio", "过路费", Category.ROAD_SIGNS),
  createWord("u511", "precedenza", "优先通行", Category.RULES),
  createWord("u514", "prefetto", "省长/行政长官", Category.DOCUMENTS),
  createWord("u530", "procedere", "行驶/行进", Category.BEHAVIOR),
  createWord("u558", "raggiungere", "达到/抵达", Category.GENERAL),
  createWord("u579", "retromarcia", "倒车", Category.VEHICLE),
  createWord("u584", "revisione", "年检/重考", Category.DOCUMENTS),
  createWord("u613", "rotatoria", "转盘/环岛", Category.ROAD_SIGNS),
  createWord("u658", "soccorso", "急救/援助", Category.ACCIDENTS),
  createWord("u665", "sorpasso", "超车", Category.RULES),
  createWord("u674", "spartitraffico", "隔离带", Category.ROAD_SIGNS),
  createWord("u678", "spegnere", "熄火/关掉", Category.VEHICLE),
  createWord("u712", "svoltare", "转弯", Category.BEHAVIOR),
  createWord("u721", "targa", "车牌", Category.DOCUMENTS),
  createWord("u728", "tornante", "险弯/拐角", Category.ROAD_SIGNS),
  createWord("u743", "trazione", "驱动/牵引", Category.VEHICLE),
  createWord("u762", "veicolo", "车辆/交通工具", Category.GENERAL),
  createWord("u778", "volante", "方向盘", Category.VEHICLE),
  createWord("u780", "zebratura", "斑马线", Category.ROAD_SIGNS),
];
